### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by EggPool** [n-y-z-o/tech#5]
https://github.com/n-y-z-o/tech/blob/e24c0b5ba03407b41c7091905134e5d57ed167e0/10_scripts/01_preferences.html#L54

Typo in maximum_conncurrent_connections_per_ip , extra n

**Comment by n-y-z-o** [comment]
This is a typo in the MeshListener source code, also. This will be corrected in the documentation when it is corrected in the source.

**Comment by n-y-z-o** [comment]
This has been corrected in both the source code and in the documentation.
